---
- name: Install and Start nginx
  hosts: webserver
  become: true
  tasks:
          - name: Install nginx
            apt:
                    name: nginx
                    state: present
          - name: Start nginx
            service:
                    name: nginx
                    state: started